---
repo_url: https://github.com/jonh-carvalho/PBE_25.2_8004
site_author: Jonh Carvalho
site_name: PBE_25.2_8004
copyright: Copyright ©️ 2025, Jonh Carvalho

nav: 
  - Home: index.md
  - Disciplina:
      - Aulas: Disciplina/aulas.md
      - Roteiros: 
          - Iniciação:
              - Design Thinking: Disciplina/Roteiros/Iniciação/04_DesignThinking.md
              - UP: Disciplina/Roteiros/Iniciação/04_UPgithub.md
          - Elaboração:
              - Requisitos: Disciplina/Roteiros/Elaboração/req_biblioteca.md
              - Casos de Uso: Disciplina/Roteiros/Elaboração/uc_biblioteca.md
              - Diagrama de Classes: Disciplina/Roteiros/Elaboração/class_biblioteca.md 
          - Construção:
              - Poo: 
                  - Intro OO: Disciplina\Roteiros\Construção\Poo\Conceitos-basicos-de-OO.pdf
                  - Procedural x OO: Disciplina\Roteiros\Construção\Poo\proceduralXpoo.ipynb
                  - Intro Python OO: Disciplina\Roteiros\Construção\Poo\poo.ipynb
                  - Python OO: Disciplina\Roteiros\Construção\Poo\Python-OO.pdf
              - Django:
                  - Intro: Disciplina\Roteiros\Construção\Django\01_Intro.md
                  - Intro Rest: Disciplina\Roteiros\Construção\Django\02_Intro Django Rest.md
                  - Streaming: 
                      - 0. Projeto Streaming: Disciplina\Roteiros\Construção\Django\Streaming\00_Projeto_Streaming.md
                      - 1. Regras de Negócio: Disciplina\Roteiros\Construção\Django\Streaming\01_Regras_Negócio_Streaming.md
                      - 2. Modelagem: Disciplina\Roteiros\Construção\Django\Streaming\02_Modelagem_Streaming.md
                      - 3. Rest Api: Disciplina\Roteiros\Construção\Django\Streaming\03_Rest_Streaming.md
                      - 4. Consume: Disciplina\Roteiros\Construção\Django\Streaming\04_Consume_Streaming.md
                      - 5. Playlists NxN: Disciplina\Roteiros\Construção\Django\Streaming\05_Playlist NxN.md
                      - 6. Shell: Disciplina\Roteiros\Construção\Django\Streaming\06_Shell_Streaming.md
                      - 7. Swagger: Disciplina\Roteiros\Construção\Django\Streaming\06_Swagger.md
                      - 8. Carga de Dados: Disciplina\Roteiros\Construção\Django\Streaming\07_Carga de Dados.md
                      - 9. CorsOrigin: Disciplina\Roteiros\Construção\Django\Streaming\08_CorsOrigin.md
                      - 10. Consume Web: Disciplina\Roteiros\Construção\Django\Streaming\09_Consume_Streaming_Web.md
                      - 11. Admin: Disciplina\Roteiros\Construção\Django\Streaming\10_Admin_Streaming.md
                      - 12. Associações: Disciplina\Roteiros\Construção\Django\Streaming\11_Associações.md
                      - 13. Autenticação: Disciplina\Roteiros\Construção\Django\Streaming\12_Autenticação.md
                      - 14. Filtros: Disciplina\Roteiros\Construção\Django\Streaming\13_Filtros.md
                      - 15. Regras de Negócio: Disciplina\Roteiros\Construção\Django\Streaming\14_Regras de Negócio.md
                      - 16. Deploy: Disciplina\Roteiros\Construção\Django\Streaming\15_Deploy.md
      - Ambiente: Disciplina/ambiente.md
      - Github: Disciplina/github.md
      - Mkdocs: Disciplina/mkdocs.md
      - CodeSpace: Disciplina/codespace.md
      - Avaliações: Disciplina/avalia.md
      - Issues e Projects: Disciplina/issues_projects.md
      - Dojo: 
          - Index: Disciplina/dojo/dojo.md
          - Setup: Disciplina/dojo/setup.md
          - TDD/Pair: Disciplina/dojo/tddpairprogramming.md
           
  - Iniciação: 
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - Cenário: Iniciacao/cenario.md
      - 5w2h: Iniciacao/5w2h.md
      - Brainstorming: Iniciacao/brainstorm.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Design Thinking: Iniciacao/design_thinking.md
    
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/espreq.md
      - Casos de Uso: Elaboracao/diagrama_casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
      - Protótipo de Baixa Fidelidade: Elaboracao/prototipo_baixa_fidelidade.md
      
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Transição:
      - Index: Transicao/index.md

  - Bibliografia: Disciplina/bibliografia.md

extra_css:
  - css/extra.css

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - mkdocs-jupyter
  
  - search

theme:
  name: material
  favicon: assets/ibmec_icon.png
  logo: assets/ibmec_logo.png
  color_mode: dark
  language: pt-BR
  user_color_mode_toggle: true
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      
  
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/react
    favicon: simple/react

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables

  - toc:
      permalink: true